config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  root 'top#index'
  
  get 'top' => 'top#index'
  
  resources :equipments do
    collection do
      get 'search', to: 'equipments#search'
    end
  end
  
  resources :characters do
    collection do
      get 'search', to: 'characters#search'
    end
  end


end

app/models/ability.rb
class Ability < ApplicationRecord
    has_many :equip_abis, dependent: :destroy
    has_many :equipments, through: :equip_abis

    has_many :chara_abis, dependent: :destroy
    has_many :characters, through: :chara_abis

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chara_abi.rb
class CharaAbi < ApplicationRecord
    belongs_to :ability
    belongs_to :character
end

app/models/character.rb
class Character < ApplicationRecord
    has_many :chara_abis, dependent: :destroy
    has_many :abilitys, through: :chara_abis
    accepts_nested_attributes_for :chara_abis, allow_destroy: true, reject_if: :all_blank
end

app/models/equip_abi.rb
class EquipAbi < ApplicationRecord
    belongs_to :equipment
    belongs_to :ability
end

app/models/equip_mate.rb
class EquipMate < ApplicationRecord
    belongs_to :equipment
    belongs_to :material
end

app/models/equipment.rb
class Equipment < ApplicationRecord
    has_many :equip_abis, dependent: :destroy
    accepts_nested_attributes_for :equip_abis, allow_destroy: true
    has_many :abilitys, through: :equip_abis
    
    has_many :equip_mates, dependent: :destroy
    accepts_nested_attributes_for :equip_mates, allow_destroy: true
    has_many :materials, through: :equip_mates
   
end

app/models/material.rb
class Material < ApplicationRecord
    has_many :equip_mates
    has_many :equipments, through: :equip_mates
end

app/models/top.rb
class Top < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/character_controller.rb
class CharacterController < ApplicationController

end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
        
    def index
        @characters = Character.all.order(:genre)
        @genre_nomal = Character.where("genre=?",'初期').order(:genre)
        @genre_mh = Character.where("genre=?",'モンハン').order(:genre)
        @genre_battle = Character.where("genre=?",'戦争').order(:genre)
        @genre_mate = Character.where("genre=?",'素材集め').order(:genre)
        # 検索機能
        @q = Character.ransack(params[:q])
        @abilitys = Ability.where("genre=? or genre=?",'キャラ','両用')
        @chara = @q.result.includes(:abilitys).order(:genre)
        @chara_nomal = @q.result.includes(:abilitys).where("characters.genre=?",'初期').order(:genre)
        @chara_mh = @q.result.includes(:abilitys).where("characters.genre=?",'モンハン').order(:genre)
        @chara_battle = @q.result.includes(:abilitys).where("characters.genre=?",'戦争').order(:genre)
        @chara_mate = @q.result.includes(:abilitys).where("characters.genre=?",'素材集め').order(:genre)
    end
    
    def search
        @characters = Character.all
        @abilitys = Ability.where("genre=? or genre=?",'キャラ','両用')
        @q = Character.search(search_params)
        @chara = @q.result.includes(:abilitys)
        @chara_nomal = @q.result.includes(:abilitys).where("characters.genre=?",'初期')
        @chara_mh = @q.result.includes(:abilitys).where("characters.genre=?",'モンハン')
        @chara_battle = @q.result.includes(:abilitys).where("characters.genre=?",'戦争')
        @chara_mate = @q.result.includes(:abilitys).where("characters.genre=?",'素材集め')
    end
    
    def new
        @character = Character.new
        @character.chara_abis.build
    end
    
    def create
        Character.create(character_params)
    end
    
    def destroy
        character = Character.find(params[:id])
        character.destroy
    end
    
    def edit
        @character = Character.find(params[:id])
    end
    
    def update
        character = Character.find(params[:id])
        character.update(character_params)
    end
    
    private
    def character_params
        params.require(:character).permit(:id, :name, :genre,
            chara_abis_attributes: [:id, :valume, :character_id, :ability_id, :_destroy, 
            abilitys_attributes:[:id, :name, :genre, :_destroy]])
    end
    
    def search_params
        params.require(:q).permit!
    end
end

app/controllers/equipment_controller.rb
class EquipmentController < ApplicationController

end

app/controllers/equipments_controller.rb
class EquipmentsController < ApplicationController
        
    def index
        @equipments = Equipment.all.order(:level)
        @part_hand = Equipment.where("part=?",'手').order(:level)
        @part_head = Equipment.where("part=?",'頭').order(:level)
        @part_body = Equipment.where("part=?",'体').order(:level)
        @part_foot = Equipment.where("part=?",'足').order(:level)
        @part_accessory = Equipment.where("part=?",'アクセ').order(:level)
    # 検索機能
        @abilitys = Ability.where("genre=? or genre=?",'装備','両用')
        @q = Equipment.ransack(params[:q])
        @equip_all = @q.result.includes(:abilitys).order(:level)
        @equip_hand = @q.result.includes(:abilitys).where("part=?",'手').order(:level)
        @equip_head = @q.result.includes(:abilitys).where("part=?",'頭').order(:level)
        @equip_body = @q.result.includes(:abilitys).where("part=?",'体').order(:level)
        @equip_foot = @q.result.includes(:abilitys).where("part=?",'足').order(:level)
        @equip_accessory = @q.result.includes(:abilitys).where("part=?",'アクセ').order(:level)
    end
    
    def search
        @equipments = Equipment.all
        @abilitys = Ability.where("genre=? or genre=?",'装備','両用')
        @q = Equipment.search(search_params)
        @equip_all = @q.result.includes(:abilitys)
        @equip_hand = @q.result.includes(:abilitys).where("part=?",'手')
        @equip_head = @q.result.includes(:abilitys).where("part=?",'頭')
        @equip_body = @q.result.includes(:abilitys).where("part=?",'体')
        @equip_foot = @q.result.includes(:abilitys).where("part=?",'足')
        @equip_accessory = @q.result.includes(:abilitys).where("part=?",'アクセ')
    end
    
    def new
        @equipment = Equipment.new
        @equipment.equip_abis.build
        @equipment.equip_mates.build
    end
    
    def create
        Equipment.create(equipment_params)
    end
    
    def destroy
        equipment = Equipment.find(params[:id])
        equipment.destroy
    end
    
    def edit
        @equipment = Equipment.find(params[:id])
        @equipment.equip_abis.build
        @equipment.equip_mates.build
    end
    
    def update
        equipment = Equipment.find(params[:id])
        equipment.update(equipment_params)
    end
    
    private
    def equipment_params
        params.require(:equipment).permit(:id, :name, :part, :level,
            equip_mates_attributes: [:id, :value, :equipment_id, :material_id, :_destroy, materials_attributes: [:id, :name, :genre, :_destroy]],
            equip_abis_attributes: [:id, :valume, :equipment_id, :ability_id, :_destroy, abilitys_attributes: [:id, :name, :_destroy]])
    end
    
    def search_params
        params.require(:q).permit!
    end
    
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def index
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/character_helper.rb
module CharacterHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/helpers/equipments_helper.rb
module EquipmentsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/character/_chara_abi_fields.html.erb
<div class="nested-fields">
  
  <%= f.collection_select(:ability_id, Ability.all, :id, :name, :prompt => true) %>

<!--以下後に消すが参考アビリティとして残す-->
<!--  <span class="close" title="Close" style="display: none;">-</span>-->

<!--      <option>----</option>-->
<!--      <optgroup label="対攻撃力">-->
<!--        <option>魔獣</option>-->
<!--        <option>幻獣</option>-->
<!--        <option>亜人</option>-->
<!--        <option>無機物</option>-->
<!--        <option>悪魔</option>-->
<!--        <option>竜</option>-->
<!--        <option>神</option>-->
<!--        <option>光輪龍</option>-->
<!--        <option>灼熱龍</option>-->
<!--        <option>究極龍</option>-->
<!--        <option>氷獄龍</option>-->
<!--        <option>晶魔</option>-->
<!--      <optgroup label="内政向け">-->
<!--        <option>建設速度</option>-->
<!--        <option>研究速度</option>-->
<!--        <option>資源生産上限</option>-->
<!--        <option>木材生産</option>-->
<!--        <option>石材生産</option>-->
<!--        <option>鉱石生産</option>-->
<!--        <option>食糧生産</option>-->
<!--        <option>魔石生産</option>-->
<!--        <option>資源保護</option>-->
<!--      <optgroup label="兵種攻撃力">-->
<!--        <option>兵士</option>-->
<!--        <option>騎兵</option>-->
<!--        <option>槍兵</option>-->
<!--        <option>弓兵</option>-->
<!--      <optgroup label="兵種防御力">-->
<!--        <option>兵士</option>-->
<!--        <option>騎兵</option>-->
<!--        <option>槍兵</option>-->
<!--        <option>弓兵</option>-->
<!--      <optgroup label="兵種訓練速度">-->
<!--        <option>兵士</option>-->
<!--        <option>騎兵</option>-->
<!--        <option>槍兵</option>-->
<!--        <option>弓兵</option> -->
<!--        <option>砲兵</option> -->
<!--      <optgroup label="その他">-->
<!--        <option>オーラ最大値</option>-->
<!--        <option>英雄移動速度</option>-->
<!--        <option>クリティカル率</option>-->
<!--        <option>オーラ消費効率</option>-->
<!--        <option>兵士維持効率</option>-->
<!--        <option>行軍速度</option>-->
<!--        <option>運搬力</option>-->
<!--        <option>装備生産速度</option>-->
<!--        <option>装備生産効率</option>  -->
<!--        <option>英雄経験値</option>-->
<!--        <option>英雄親愛度</option>-->
<!--      <optgroup label="戦争向け">-->
<!--        <option>防御兵器生産効率</option>-->
<!--        <option>破損兵器修理速度</option>-->
<!--        <option>治癒速度</option>-->
<!--        <option>治癒効率</option></select>-->
  <%= f.text_field :value, html: {class: 'form-control'} %>
  <!--投稿画面に行こうとするとエラー　内容【undefined method `new_record?' for nil:NilClass】-->

</div>

app/views/character/destroy.html.erb
  <div class="success">
    <h3>
      削除が完了しました。
    </h3>
    <a class="btn" href="/character">投稿一覧へ戻る</a>
  </div>

app/views/character/edit.html.erb
<div class="panel panel-default">
  <%= form_for("/character/#{@character.id}", method: :patch ) do |f| %>
    <h3>
      編集する
    </h3>
    <div class="panel-body">
      <div class="form-group">
        <label class="col-sm-2 control-label">英雄名</label>
        <input type="text" name="image" value="<%= @character.name %>" placeholder="" autofocus="true">
      </div>
      
      <div class="form-group">
        <label  class="col-sm-2 control-label">アビリティ</label>
          <%= f.fields_for :chara_abis do |abi| %>
            <%= render 'chara_abi_edit_fields', f: abi %>
          <% end %>
      </div>
    </div>
              
    <%= f.submit "編集" %>
  <% end %>
</div>

app/views/character/new.html.erb
<div class="container">
    <% @character = Character.new unless@character %>
    <%= form_for @character, url: character_new_path do |f| %>
      <div class="panel panel-default">
        <div class="panel-heading">キャラ登録</div>
        
        <div class="panel-body">
          <form class="form-horizontal">
            <div class="form-group">
              <label class= "col-sm-2 control-label">名前</label>
              <div class="col-sm-10">
                <%= f.text_field :name, html: {class: 'form-control'} %>
              </div>
            </div>

            <div class="form-group">
              <label class="col-sm-2 control-label">アビリティ</label>
                <%= f.fields_for :chara_abis do |abi| %>
                  <%= render 'chara_abi_fields', f: abi %>
                    <div id="links">
                      <%= link_to_add_association "アビリティ追加", f, :chara_abis %><br/>
                    </div>
                <% end %>
            </div>

            <div class="form-group">
              <div class="col-sm-offset-2 col-sm-10">
                 <%= f.submit "登録" %>
              </div>
            </div>
          </form>
        </div>
      </div>
    <% end %>
</div>

app/views/character/update.html.erb
<div class="success">
    <h3>
      更新が完了しました。
    </h3>
    <a class="btn" href="/character">投稿一覧へ戻る</a>
</div>

app/views/characters/_chara_abi_edit_fields.html.erb
<div class="nested-fields">
  <%= f.collection_select(:ability_id, Ability.all, :id, :name, :prompt => true) %>
  <%= f.text_field :valume,  html: {class: 'form-control'} %>
</div>

app/views/characters/_chara_abi_fields.html.erb
<div class="nested-fields">
  <%= f.collection_select(:ability_id, Ability.all, :id, :name, :prompt => true) %>
  <%= f.text_field :valume, html: {class: 'form-control'} %>
  <%= link_to_remove_association "削除", f %>
</div>

app/views/characters/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-info navbar-fixed-top">
  <a class="navbar-brand" href="/">TOP</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse navbar-left" id="navbarNavAltMarkup">
    <ul class="navbar-nav">
        
        <li class="nav-item">
          <%= link_to '　　装備　　', '/equipments', class: 'btn btn-danger' %>
        </li>
        
        <li class="nav-item">
          <%= link_to '　　英雄　　', '/characters', class: 'btn btn-info' %>
        </li>
        
        <li class="nav-item">
          <%= link_to '　　初心者向け/小ネタ　　', '/', class: 'btn btn-warning' %>
        </li>
    </ul>
  </div>
  
  
  <div class="collapse navbar-collapse navbar-right" id="navbarNavAltMarkup">
    <ul class="navbar-nav">
        
        <li class="nav-item">
          <!--ログイン-->
            <% if user_signed_in? %>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn btn-dark' %>
            <% else %>
                <%= link_to "ログイン", new_user_session_path, class: 'btn btn-dark' %>
            <% end %>
        </li>
    </ul>
  </div>
</nav>

app/views/characters/_navsearch.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-info navbar-fixed-top">
  <a class="navbar-brand" href="/">TOP</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse navbar-left" id="navbarNavAltMarkup">
    <ul class="navbar-nav">
        
        <li class="nav-item">
          <%= link_to '　　装備　　', '/equipments', class: 'btn btn-danger' %>
        </li>
        
        <li class="nav-item">
          <%= link_to '　　英雄　　', '/characters', class: 'btn btn-info' %>
        </li>
        
        <li class="nav-item">
          <%= link_to '　　初心者向け/小ネタ　　', '/', class: 'btn btn-warning' %>
        </li>
    </ul>
  </div>
  
  
  <div class="collapse navbar-collapse navbar-right" id="navbarNavAltMarkup">
    <ul class="navbar-nav">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle bg-primary" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              アビリティ絞り込み
            </a>
            <div class="dropdown-menu scrollable-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="#">
                  <%= search_form_for(@q, url:search_characters_path) do |f| %>
                      <%= f.collection_check_boxes :abilitys_id_eq_all, @abilitys, :id, :name do |b| %>
                        <%= b.label { b.check_box + b.text } %></br>
                      <% end %>
                    <%= submit_tag "検索" %>
                    <% end %>
              </a>
            </div>
      </li>
        
        <li class="nav-item">
          <!--ログイン投稿-->
          <% if user_signed_in? %>
              <%= link_to 'キャラ投稿へ', "/characters/new", method: :get, class: 'btn btn-secondary' %>
          <% end %>
        </li>
        
        <li class="nav-item">
          <!--ログイン-->
            <% if user_signed_in? %>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn btn-dark' %>
            <% else %>
                <%= link_to "ログイン", new_user_session_path, class: 'btn btn-dark' %>
            <% end %>
        </li>
    </ul>
  </div>
</nav>

app/views/characters/_search.html.erb
<ul class="nav nav-tabs">
  
  <li class="nav-item">
    <a href="#tab1" class="nav-link" data-toggle="tab">全員</a>
  </li>  
  <li class="nav-item">
    <a href="#tab2" class="nav-link" data-toggle="tab">モンハン</a>
  </li>
  <li class="nav-item">
    <a href="#tab3" class="nav-link" data-toggle="tab">戦争</a>
  </li>
  <li class="nav-item">
    <a href="#tab4" class="nav-link" data-toggle="tab">素材集め</a>
  </li>
  <li class="nav-item">
    <a href="#tab5" class="nav-link" data-toggle="tab">初期</a>
  </li>
</ul>


<div class="tab-content">
  <div id="tab1" class="tab-pane active">
            <div class="row">
            <div class="col-6">
                <div class="row">
                  <% @chara.each do |character| %>
                    <div class="col-6">
                    <div class="panel panel-default col-auto col-offset-1">
                      <div id="name" class="panel-heading lead col-auto"><%= character.name %></div>
                      <div class="panel-body">
                        <p>アビリティ</p>
                        <% character.chara_abis.each do |characters_abilitys| %>
                        <span><%= characters_abilitys.ability.name %></span>
                        <span><%= characters_abilitys.valume %>%</span>
                        <% end %>
                        <div class="panel-footer">
                          <% if user_signed_in? %>
                            <%= link_to '編集', "/characters/#{character.id}/edit", method: :get %>
                            <%= link_to '削除', "/characters/#{character.id}", method: :delete %>
                          <% end %> 
                        </div>  
                      </div>      
                    </div>
                    </div>
                  <% end %>
                </div>
            </div>
            </div>
        </div>
        
        <div id="tab2" class="tab-pane">
            <div class="row">
            <div class="col-6">
                <div class="row">
                  <% @chara_mh.each do |character| %>
                    <div class="col-6">
                    <div class="panel panel-default col-auto col-offset-1">
                      <div id="name" class="panel-heading lead col-auto"><%= character.name %></div>
                      <div class="panel-body">
                        <p>アビリティ</p>
                        <% character.chara_abis.each do |characters_abilitys| %>
                        <span><%= characters_abilitys.ability.name %></span>
                        <span><%= characters_abilitys.valume %>%</span>
                        <% end %>
                        <div class="panel-footer">
                          <% if user_signed_in? %>
                            <%= link_to '編集', "/characters/#{character.id}/edit", method: :get %>
                            <%= link_to '削除', "/characters/#{character.id}", method: :delete %>
                          <% end %> 
                        </div>  
                      </div>      
                    </div>
                    </div>
                  <% end %>
                </div>
            </div>
            </div>
        </div>
        
        <div id="tab3" class="tab-pane">
          <div class="row">
            <div class="col-6">
                <div class="row">
                  <% @chara_battle.each do |character| %>
                    <div class="col-6">
                    <div class="panel panel-default col-auto col-offset-1">
                      <div id="name" class="panel-heading lead col-auto"><%= character.name %></div>
                      <div class="panel-body">
                        <p>アビリティ</p>
                        <% character.chara_abis.each do |characters_abilitys| %>
                        <span><%= characters_abilitys.ability.name %></span>
                        <span><%= characters_abilitys.valume %>%</span>
                        <% end %>
                        <div class="panel-footer">
                          <% if user_signed_in? %>
                            <%= link_to '編集', "/characters/#{character.id}/edit", method: :get %>
                            <%= link_to '削除', "/characters/#{character.id}", method: :delete %>
                          <% end %> 
                        </div>  
                      </div>      
                    </div>
                    </div>
                  <% end %>
                </div>
            </div>
            </div>
        </div>
        
        <div id="tab4" class="tab-pane">
            <div class="row">
            <div class="col-6">
                <div class="row">
                  <% @chara_mate.each do |character| %>
                    <div class="col-6">
                    <div class="panel panel-default col-auto col-offset-1">
                      <div id="name" class="panel-heading lead col-auto"><%= character.name %></div>
                      <div class="panel-body">
                        <p>アビリティ</p>
                        <% character.chara_abis.each do |characters_abilitys| %>
                        <span><%= characters_abilitys.ability.name %></span>
                        <span><%= characters_abilitys.valume %>%</span>
                        <% end %>
                        <div class="panel-footer">
                          <% if user_signed_in? %>
                            <%= link_to '編集', "/characters/#{character.id}/edit", method: :get %>
                            <%= link_to '削除', "/characters/#{character.id}", method: :delete %>
                          <% end %> 
                        </div>  
                      </div>      
                    </div>
                    </div>
                  <% end %>
                </div>
            </div>
            </div>
        </div>
        
        <div id="tab5" class="tab-pane">
            <div class="row">
            <div class="col-6">
                <div class="row">
                  <% @chara_nomal.each do |character| %>
                    <div class="col-6">
                    <div class="panel panel-default col-auto col-offset-1">
                      <div id="name" class="panel-heading lead col-auto"><%= character.name %></div>
                      <div class="panel-body">
                        <p>アビリティ</p>
                        <% character.chara_abis.each do |characters_abilitys| %>
                        <span><%= characters_abilitys.ability.name %></span>
                        <span><%= characters_abilitys.valume %>%</span>
                        <% end %>
                        <div class="panel-footer">
                          <% if user_signed_in? %>
                            <%= link_to '編集', "/characters/#{character.id}/edit", method: :get %>
                            <%= link_to '削除', "/characters/#{character.id}", method: :delete %>
                          <% end %> 
                        </div>  
                      </div>      
                    </div>
                    </div>
                  <% end %>
                </div>
            </div>
            </div>
        </div>
        
</div>

app/views/characters/create.html.erb
<%= render 'navbar' %>

<div class="container">
  <div class="panel panel-default">
    <h3>
      投稿が完了しました。
    </h3>
    <a class="btn" href="/characters">キャラ一覧へ戻る</a>
    <a class="btn" href="/characters/new">キャラ投稿へ戻る</a>
  </div>
</div>

app/views/characters/destroy.html.erb
<%= render 'navbar' %>

  <div class="success">
    <h3>
      削除が完了しました。
    </h3>
    <a class="btn" href="/characters">投稿一覧へ戻る</a>
  </div>

app/views/characters/index.html.erb
<%= render 'navsearch' %>

<!--種類別タブ-->
<%= render 'tab' %>

app/views/characters/new.html.erb
<%= render 'navbar' %>

<div class="container">
    <% @character = Character.new unless@character %>
    <%= form_for @character, url: characters_path do |f| %>
      <div class="panel panel-default">
        <div class="panel-heading">キャラ登録</div>
        
        <div class="panel-body">
            <div class="form-group">
              <label class= "col-sm-3 control-label">名前</label>
                <div class="col-sm-9">
                  <%= f.text_field :name, html: {class: 'form-control'} %>
                </div>
            </div>

            <div class="form-group">
              <label class="col-sm-2 control-label">アビリティ</label>
                <%= f.fields_for :chara_abis do |abi| %>
                  <%= render 'chara_abi_fields', f: abi %>
                    <div id="links">
                      <%= link_to_add_association "アビリティ追加", f, :chara_abis %><br/>
                    </div>
                <% end %>
            </div>
            
            <div class="form-group">
              <label class="col-12 control-label">種類</label>
              <div class="col-sm-10 radio">
                <label><%= f.radio_button :genre, "モンハン" %>モンハン</label>
                <label><%= f.radio_button :genre, "素材集め" %>素材集め</label>
                <label><%= f.radio_button :genre, "戦争" %>戦争</label>
              </div>
            </div>

            <div class="form-group">
              <div class="col-sm-offset-2 col-sm-10">
                 <%= f.submit "登録" %>
              </div>
            </div>
          </form>
        </div>
      </div>
    <% end %>
</div>

app/views/equipment/new.html.erb
 <div class="container">
   <% @equipment = Equipment.new unless@equipment %>
   <%= form_for @equipment, url: equipment_new_path do |f| %>
      <div class="panel panel-default">
        <div class="panel-heading">装備登録</div>
        
        <div class="panel-body">
          <form class="form-horizontal">
            <div class="form-group">
              <label class= "col-sm-2 control-label">名前</label>
              <div class="col-sm-10">
                <%= f.text_field :name, html: {class: 'form-control'} %>
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-2 control-label">装備部位</label>
              <div class="col-sm-10 radio">
                <label><%= f.radio_button :part, "手" %>手</label>
                <label><%= f.radio_button :part, "頭" %>頭</label>
                <label><%= f.radio_button :part, "胴" %>胴</label>
                <label><%= f.radio_button :part, "足" %>足</label>
                <label><%= f.radio_button :part, "アクセサリー" %>アクセサリー</label>
              </div>
            </div>
            
            <div class="form-group">
              <label class= "col-sm-2 control-label">装備レベル</label>
              <div class="col-sm-10 radio">
                <label><%= f.radio_button :level, "1" %>1</label>
                <label><%= f.radio_button :level, "2" %>2</label>
                <label><%= f.radio_button :level, "4" %>4</label>
                <label><%= f.radio_button :level, "8" %>8</label>
                <label><%= f.radio_button :level, "12" %>12</label>
                <label><%= f.radio_button :level, "16" %>16</label>
                <label><%= f.radio_button :level, "20" %>20</label>
                <label><%= f.radio_button :level, "24" %>24</label>
                <label><%= f.radio_button :level, "28" %>28</label>
                <label><%= f.radio_button :level, "32" %>32</label>
                <label><%= f.radio_button :level, "36" %>36</label>
                <label><%= f.radio_button :level, "40" %>40</label>
                <label><%= f.radio_button :level, "44" %>44</label>
                <label><%= f.radio_button :level, "46" %>46</label>
              </div>
            </div>
            

            <div class="form-group">
              <label class="col-sm-2 control-label">アビリティ</label>
                <%= f.fields_for :equip_abis do |abi| %>
                  <%= render 'equip_abi_fields', f: abi %>
                    <div id="links">
                      <%= link_to_add_association "アビリティ追加", f, :equip_abis %><br/>
                    </div>
                <% end %>
            </div>
            
            <div class="form-group">
              <label class="col-sm-2 control-label">合計要求素材</label>
                <%= f.fields_for :equip_mates do |material| %>
                  <%= render 'equip_mate_fields', f: material %>
                  <div id="links">
                    <%= link_to_add_association "素材追加", f, :equip_mates %><br/>
                  </div>
                <% end %>
            </div>
            <div class="form-group">
              <div class="col-sm-offset-2 col-sm-10">
                 <%= f.submit "登録" %>
              </div>
            </div>
          </form>
          
        </div>
      </div>
    <% end %>
</div>